name: Docker
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Docker
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build
      uses: actions/docker/cli@master
      with:
        args: build -t djerfy/bonjourmadame-api-server:latest .
    - name: Login
      uses: actions/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
    - name: Push
      uses: actions/docker/cli@master
      with:
        args: push djerfy/bonjourmadame-api-server:latest
