name: Docker
on:
  push:
    tags:
    - v*
jobs:
  build:
    name: Docker
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build
      run: |
        docker build -t djerfy/bonjourmadame-api-server:${GITHUB_SHA} .
        docker build -t djerfy/bonjourmadame-api-server:latest .
    - name: Login 
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Push
      run: |
        docker push djerfy/bonjourmadame-api-server:${GITHUB_SHA}
        docker push djerfy/bonjourmadame-api-server:latest
    - name: Logout
      run: docker logout
